services:
  empresaapi:
    image: "empresaltda"
    container_name: "empresa_container"
    build:
      context: .
    depends_on:
      - "database"
    ports:
      - "5000:8080"
    restart: "always"
    environment:
      - APSNETCORE_ENVIROMENT=Development
  database:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: master
    ports:
      - 3306:3306
    volumes:
      - ./database-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
